// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAabBTYdzu92eaYJKcDGQFenNaGG1QIaU4',
    appId: '1:1086864728570:web:4e5e712281ca51d42b8443',
    messagingSenderId: '1086864728570',
    projectId: 'ptimm1',
    authDomain: 'ptimm1.firebaseapp.com',
    storageBucket: 'ptimm1.firebasestorage.app',
    measurementId: 'G-299XVHB2T4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrggrv0WjJouzoff5iqyDPJLwUuRjaxDE',
    appId: '1:1086864728570:android:1d613763567fadc52b8443',
    messagingSenderId: '1086864728570',
    projectId: 'ptimm1',
    storageBucket: 'ptimm1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHSrSdIQZb_lJOB52De7kkzh1ges1nPjU',
    appId: '1:1086864728570:ios:4b400c62cfd4b01e2b8443',
    messagingSenderId: '1086864728570',
    projectId: 'ptimm1',
    storageBucket: 'ptimm1.firebasestorage.app',
    iosBundleId: 'com.example.ptimmApp1',
  );
}
